

/* auto generate */


export const enum Token {
    YYEOF                                    = 0,
    YYerror                                  = 256,
    YYUNDEF                                  = 257,
    TK_NUMBER                                = 258,
    TK_IF                                    = 259,
    TK_ELSE                                  = 260,
    TK_FOR                                   = 261,
    TK_WHILE                                 = 262,
    TK_DO                                    = 263,
    TK_CONST                                 = 264,
    TK_IDEN                                  = 265,
    TK_PUBLIC                                = 266,
    OP_LOGIC_OR                              = 267,
    OP_LOGIC_AND                             = 268,
    OP_EQ                                    = 269,
    OP_NE                                    = 270,
    OP_LE                                    = 271,
    OP_GE                                    = 272,
    OP_SHIFT_LEFT                            = 273,
    OP_SHIFT_RIGHT                           = 274,
    OP_SHIFT_RIGHT_U                         = 275,
    PREC_THEN                                = 276,

$MAX_TOKEN_VALUE = 276

}


export const enum Action {
    AC_GOAL_1                                = 2,
    AC_GOAL_2                                = 3,
    AC_PUBLIC_SIZE_0                         = 4,
    AC_PUBLIC_SIZE_X                         = 5,
    AC_CONST_STATEMENT                       = 10,
    AC_DECL_1                                = 11,
    AC_DECL_X                                = 12,
    AC_EMPTY_STMT                            = 22,
    AC_BLOCK_EMPTY                           = 23,
    AC_BLOCK_DECLARE                         = 24,
    AC_EXPRESSION_DECLARE                    = 25,
    AC_IF_STATEMENT                          = 26,
    AC_IF_ELSE_STATEMENT                     = 27,
    AC_WHILE_STATEMENT                       = 28,
    AC_DO_WHILE_STATEMENT                    = 29,
    AC_FOR_STATEMENT                         = 30,
    AC_OPT_EXPR_NULL                         = 31,
    AC_EXPR_LOGIC_OR                         = 34,
    AC_EXPR_LOGIC_AND                        = 35,
    AC_EXPR_BIT_OR                           = 36,
    AC_EXPR_BIT_XOR                          = 37,
    AC_EXPR_BIT_AND                          = 38,
    AC_EXPR_EQ                               = 39,
    AC_EXPR_NE                               = 40,
    AC_EXPR_LE                               = 41,
    AC_EXPR_GE                               = 42,
    AC_EXPR_GT                               = 43,
    AC_EXPR_LT                               = 44,
    AC_EXPR_SHIFT_LEFT                       = 45,
    AC_EXPR_SHIFT_RIGHT                      = 46,
    AC_EXPR_SHIFT_RIGHT_U                    = 47,
    AC_EXPR_ADD                              = 48,
    AC_EXPR_SUB                              = 49,
    AC_EXPR_MUL                              = 50,
    AC_EXPR_DIV                              = 51,
    AC_EXPR_MOD                              = 52,
    AC_EXPR_UNARY_ADD                        = 54,
    AC_EXPR_UNARY_SUB                        = 55,
    AC_EXPR_BIT_NOT                          = 56,
    AC_EXPR_LOGIC_NOT                        = 57,
    AC_PRI_EXPR_0                            = 58,
    AC_PRI_IDEN                              = 59,
    AC_PRI_NUMBER                            = 60,
    AC_CALL_0                                = 62,
    AC_CALL_X                                = 63,
    AC_ARGLIST_1                             = 64,
    AC_ARGLIST_X                             = 65,
    AC_INPUT_END                             = 68,
    AC_INPUT_BEGIN                           = 69,
    AC_INPUT_OFFSET                          = 70,
    AC_INPUT_SIZE_1                          = 71,
    AC_INPUT_SIZE_2                          = 72,
    AC_INPUT_EXPR                            = 77,
    AC_INPUT_EXTERN                          = 78,
    AC_OUTPUT_STMT                           = 79,
    AC_OUTPUT_OFFSET                         = 80,
    AC_OUTPUT_TYPE_BUFFER                    = 81,
    AC_OUTPUT_TYPE_INTEGER                   = 82,
    AC_OUTPUT_SIZE                           = 83,

}

