#pragma once

#ifndef __WTINC_RV32IM_ATOMIC_ROCKEY_PREDEF_H__
#define __WTINC_RV32IM_ATOMIC_ROCKEY_PREDEF_H__

/**
 *!
 */
#if defined(rLANG_CONFIG_ENABLE_ATOMC_WORLD) && rLANG_CONFIG_ENABLE_ATOMC_WORLD <= 0
#error "Invalid rLANG_CONFIG_ENABLE_ATOMC_WORLD Version!"
#endif /* rLANG_CONFIG_ENABLE_ATOMC_WORLD */

#if defined(rLANG_CONFIG_ENABLE_COSMO_WORLD) && rLANG_CONFIG_ENABLE_COSMO_WORLD <= 0
#error "Invalid rLANG_CONFIG_ENABLE_COSMO_WORLD Version!"
#endif /* rLANG_CONFIG_ENABLE_COSMO_WORLD */

#if defined(rLANG_CONFIG_ENABLE_ATOMC_WORLD) && defined(rLANG_CONFIG_ENABLE_COSMO_WORLD)
#error "rLANG_CONFIG_ENABLE_ATOMC_WORLD + rLANG_CONFIG_ENABLE_COSMO_WORLD"
#endif /* rLANG_CONFIG_ENABLE_ATOMC_WORLD + rLANG_CONFIG_ENABLE_COSMO_WORLD */

#if !defined(rLANG_CONFIG_ENABLE_ATOMC_WORLD) && !defined(rLANG_CONFIG_ENABLE_COSMO_WORLD)
#define rLANG_CONFIG_ENABLE_COSMO_WORLD
#endif /* !rLANG_CONFIG_ENABLE_ATOMC_WORLD + !rLANG_CONFIG_ENABLE_COSMO_WORLD */

/**
 *!
 */
#define rLANG_CONFIG_ROCKEY_DONGLE_WORLD 1
#define rLANG_CONFIG_ENABLE_KERNEL_MODE 1
#define rLANG_CONFIG_MINIMAL_WORLD  1
#define rLANG_CONFIG_MINIMAL

#endif /*  __WTINC_RV32IM_ATOMIC_ROCKEY_PREDEF_H__ */
